### ISSUE TITLE
[10.0] Stock Analytic, When I try to confirm a stock picking

### ISSUE THREAD

**Issue by GrupoAlvamex** [OCA/account-analytic#194]
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/stock/wizard/stock_immediate_transfer.py", line 36, in process
    return self.pick_id.do_transfer()
  File "/odoo/odoo-server/addons/stock/models/stock_picking.py", line 907, in do_transfer
    todo_moves.action_done()
  File "/odoo/odoo-server/addons/sale_stock/models/stock.py", line 22, in action_done
    result = super(StockMove, self).action_done()
  File "/odoo/odoo-server/addons/stock_account/models/stock.py", line 188, in action_done
    res = super(StockMove, self).action_done()
  File "/odoo/odoo-server/addons/mrp/models/stock_move.py", line 306, in action_done
    return super(StockMove, self-production_moves).action_done()
  File "/odoo/odoo-server/addons/stock/models/stock_move.py", line 856, in action_done
    dest_package_id=quant_dest_package_id, entire_pack=entire_pack)
  File "/odoo/odoo-server/addons/stock/models/stock_quant.py", line 198, in quants_move
    quants_move_sudo._quant_update_from_move(move, location_to, dest_package_id, lot_id=lot_id, entire_pack=entire_pack)
  File "/odoo/odoo-server/addons/stock_account/models/stock.py", line 172, in _quant_update_from_move
    self._account_entry_move(move)
  File "/odoo/custom/odoo-mexico-localization/argil_account_per_warehouse/model/metodos.py", line 195, in _account_entry_move
    self.with_context(force_company=force_company)._create_account_move_line(move, acc_src, acc_dest, journal_id)
  File "/odoo/odoo-server/addons/stock_account/models/stock.py", line 134, in _create_account_move_line
    move_lines = move._prepare_account_move_line(qty, cost, credit_account_id, debit_account_id)
  File "/odoo/custom/odoo-mexico-localization/stock_move_entries/model/metodos.py", line 13, in _prepare_account_move_line
    res = super(stock_move, self)._prepare_account_move_line(qty, cost, credit_account_id, debit_account_id)
  File "/odoo/custom/addons/stock_analytic/models/stock.py", line 30, in _prepare_account_move_line
    if res[num][2]["account_id"] != self.product_id.\
IndexError: list index out of range

**Comment by GrupoAlvamex** [comment]
I cancel all the transfers with this problem and
