### ISSUE TITLE
Analytic Report - Error: 'active_ids' is not defined

### ISSUE THREAD

**Issue by cloudition** [OCA/account-analytic#316]
https://github.com/OCA/account-analytic/blob/6368c83cc6ffa16ccf9b28930cd344f5af67f8c4/account_analytic_parent/views/account_analytic_account_view.xml#L34

This line is causing a error when you go to "Accounting" -> "Reporting" -> "Analytic Report". Open the dropdown of a report line and click on "Analytic Entries".

```
Error:
Uncaught Error: NameError: name 'active_ids' is not defined

http://localhost:8068/web/content/80003-061ff22/web.assets_backend.js:145
Traceback:
Error: NameError: name 'active_ids' is not defined
    at PY_ensurepy (http://localhost:8068/web/content/80003-061ff22/web.assets_backend.js:145:65)
    at Object.py.evaluate (http://localhost:8068/web/content/80003-061ff22/web.assets_backend.js:261:8)
    at Object.py.evaluate (http://localhost:8068/web/content/80003-061ff22/web.assets_backend.js:267:111)
    at Object.py.evaluate (http://localhost:8068/web/content/80003-061ff22/web.assets_backend.js:269:99)
    at Object.py.eval (http://localhost:8068/web/content/80003-061ff22/web.assets_backend.js:274:284)
    at http://localhost:8068/web/content/80003-061ff22/web.assets_backend.js:413:136
    at Function._.each._.forEach (http://localhost:8068/web/content/79891-c9d393e/web.assets_common.js:12:558)
    at _.<computed> [as each] (http://localhost:8068/web/content/79891-c9d393e/web.assets_common.js:69:526)
    at eval_domains (http://localhost:8068/web/content/80003-061ff22/web.assets_backend.js:412:265)
    at Object.pyeval [as eval] (http://localhost:8068/web/content/80003-061ff22/web.assets_backend.js:428:24)
```

**Comment by astirpe** [comment]
@cloudition I'm not able to reproduce the issue in Odoo 12.0 on Runbot.
Domain `[('account_id', 'child_of', active_ids)]` seems working to me.

**Comment by cloudition** [comment]
@astirpe Thx for the quick answer. It seems to be a interaction between the OCA `account_analytic_parent `module and the enterprise `account_reports `module... The error only occures when you go to Enterprise "Accounting" -> "Reporting" -> "Analytic Report". Open the dropdown of a report line and click on "Analytic Entries".

**Comment by astirpe** [comment]
OK I reproduced it locally. :+1: 
Please check my code review in https://github.com/OCA/account-analytic/pull/317
