### ISSUE TITLE
[13.0] analytic_tag_dimension write

### ISSUE THREAD

**Issue by baimont** [OCA/account-analytic#392]
Hi,

I had a problem on a particular line of code following this commit: 
https://github.com/OCA/account-analytic/commit/7638f78b1f74f4d5c23e526a241ffc3c62dbfec4#diff-6310b4c28c47b180178a9fdcc6259bec67db74515cdf77867ffc19c9b85d0677

The line is:
https://github.com/OCA/account-analytic/blob/5692b4cf2dcf9ea6e9102e4a89a506d8aaabb9a5/analytic_tag_dimension/models/analytic_dimension_line.py#L23

This line crashes if you update vals like this:
`"analytic_tag_ids": self.analytic_tag_ids.ids,`
And so you have to adapt all your analytic tags vals to:
`"analytic_tag_ids": [(6, 0, self.analytic_tag_ids.ids)],`

It is not a big problem but I'm wondering: if Odoo allows you to write the first line and that it works, shouldn't analytic_tag_dimension manage it?

@pedrobaeza

**Comment by pedrobaeza** [comment]
Pass the stacktrace you get and the content of the `vals` dictionary.

**Comment by baimont** [comment]
Stacktrace: 
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/addons/web/controllers/main.py", line 1343, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/addons/sale_account_taxcloud/models/sale_order.py", line 19, in action_confirm
    return super(SaleOrder, self).action_confirm()
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/addons/sale_management/models/sale_order.py", line 124, in action_confirm
    res = super(SaleOrder, self).action_confirm()
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/addons/sale/models/sale.py", line 844, in action_confirm
    self.with_context(context)._action_confirm()
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/addons/fieldservice_sale_stock/models/sale_order.py", line 36, in _action_confirm
    res = super()._action_confirm()
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/addons/sale_timesheet/models/sale_order.py", line 82, in _action_confirm
    result = super(SaleOrder, self)._action_confirm()
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/addons/fieldservice_sale/models/sale_order.py", line 146, in _action_confirm
    self.order_line._field_service_generation()
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/addons/fieldservice_sale/models/sale_order_line.py", line 141, in _field_service_generation
    so_fo_mapping = sale._field_find_fsm_order()
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/addons/fieldservice_sale/models/sale_order.py", line 134, in _field_find_fsm_order
    fsm_order = so._field_create_fsm_order()[so.id]
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/addons/fieldservice_sale/models/sale_order.py", line 90, in _field_create_fsm_order
    fsm_order = self.env["fsm.order"].sudo().create(values)
  File "<decorator-gen-176>", line 2, in create
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/addons/analytic_tag_dimension/models/analytic_dimension_line.py", line 61, in create
    vals = self._handle_analytic_dimension(vals)
  File "/home/benoit/.virtualenvs/odoo-eri/lib/python3.6/site-packages/odoo/addons/analytic_tag_dimension/models/analytic_dimension_line.py", line 22, in _handle_analytic_dimension
    if command[0] == 0:
TypeError: 'int' object is not subscriptable

vals:
{'location_id': 2, 'location_directions': False, 'request_early': False, 'todo': '<p><br></p>', 'category_ids': [(6, 0, [])], 'sale_id': 28, 'company_id': 1, 'short_name': 'S00027', 'customer_id': 10, 'invoicing_address_id': 10, 'delivery_zone_id': False, 'project_id': 9, 'analytic_account_id': 27, 'analytic_tag_ids': [6, 8]}

**Comment by pedrobaeza** [comment]
It seems very weird, as the write is always normalized. It seems you have other modules that denormalizes the passed vals.
