### ISSUE TITLE
Questions about analytic_secondaxis, analytic_secondaxis_project, analytic_secondaxis_timesheet?

### ISSUE THREAD

**Issue by gityopie** [OCA/account-analytic#48]
Hello,

Why those modules has installable False by default?
I tried to make it True, I mean installable = True
but then I got another error (run over odoo v8)  

here the log:  

 2015-12-16 10:25:04,587 19408 CRITICAL test openerp.modules.module: Couldn't load module analytic_secondaxis
2015-12-16 10:25:04,588 19408 CRITICAL test openerp.modules.module: No module named osv
2015-12-16 10:25:04,588 19408 CRITICAL test openerp.service.server: Failed to initialize database `test`.
Traceback (most recent call last):
  File "/home/yopiangi/Workspaces/odoo/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/yopiangi/Workspaces/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/yopiangi/Workspaces/odoo/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/yopiangi/Workspaces/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/yopiangi/Workspaces/odoo/openerp/modules/loading.py", line 143, in load_module_graph
    load_openerp_module(package.name)
  File "/home/yopiangi/Workspaces/odoo/openerp/modules/module.py", line 315, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/home/yopiangi/Workspaces/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/yopiangi/Workspaces/project/addons-community/oca_account-analytic/analytic_secondaxis/**init**.py", line 32, in <module>
    from . import analytic_secondaxis
  File "/home/yopiangi/Workspaces/project/addons-community/oca_account-analytic/analytic_secondaxis/analytic_secondaxis.py", line 32, in <module>
    from osv import fields
ImportError: No module named osv  

Thank you.

**Comment by pedrobaeza** [comment]
That's because they are actually not installable because they are not migrated to the version you are trying.
